/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// package virtualpetsamok;

// import org.junit.jupiter.api.Test;
// import static org.junit.jupiter.api.Assertions.*;

// class AppTest {

    // @Test
    // public void createVirtualCatObject() {
    //     VirtualCat testVirtualCat = new VirtualCat();
    //     assertNotNull(testVirtualCat, "class not created");
    // }

    // @Test
    // public void createVirtualDogObject() {
    //     VirtualDog testVirtualDog = new VirtualDog();
    //     assertNotNull(testVirtualDog, "class not created");
    // }
// }
